default: &default
  adapter: mysql2
  encoding: utf8
  username: rails_user
  password: password123
  host: localhost

development:
  <<: *default
  database: oivan_assesment_project_development

test:
  adapter: mysql2
  encoding: utf8
  database: oivan_assesment_project_test
  username: rails_user
  password: password123
  host: localhost

production:
  <<: *default
  database: oivan_assesment_project_production
  username: rails_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
