default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db  # Changed from localhost

development:
  <<: *default
  database: oivan_assesment_project_development

test:
  <<: *default  # Now it inherits host: db from default
  database: oivan_assesment_project_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>